[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install --omit=dev"]

[phases.build]
cmds = ["echo 'Build skipped - using pre-compiled dist'"]

[start]
<<<<<<< HEAD
cmd = "cd backend && node dist/server.js"
=======
cmd = "cd backend && node dist/server.js"
>>>>>>> 602a3b8ba0465325574852ae9b588f8e32efd5a0
